"""Type stub for the optional compiled speedup extension (``_cext.c``).

Not built by every install (see ``setup.py`` — a missing/broken C toolchain
skips it silently), so this module may not actually be importable; the
stub only describes its shape for static checking of ``backend.py``.
"""

def build_reparse_buffer(tag: int, subst_name: str, print_name: str, flags: int = 0) -> bytes: ...
def parse_reparse_buffer(data: bytes) -> tuple[int, int, str, str]: ...
def set_reparse_point(path: str, buffer: bytes) -> None: ...
def get_reparse_buffer(path: str) -> bytes: ...
def delete_reparse_point_ioctl(path: str, tag: int) -> None: ...
def create_hard_link(src: str, dst: str) -> None: ...
def get_link_count(path: str) -> int: ...
def get_file_reference_number(path: str) -> int: ...
def get_ntfs_file_record(volume_root: str, frn: int) -> bytes: ...
def volume_root(path: str) -> str: ...
def query_volume_flags(path: str, use_cache: bool = False) -> int: ...
def clear_volume_cache() -> None: ...
def ensure_privileges() -> None: ...
def reset_privileges_for_tests() -> None: ...
