"""Win32/NTFS constants shared by every backend."""
from __future__ import annotations

# Generic access
GENERIC_READ = 0x80000000
GENERIC_WRITE = 0x40000000

# Sharing
FILE_SHARE_READ = 0x00000001
FILE_SHARE_WRITE = 0x00000002
FILE_SHARE_DELETE = 0x00000004
FILE_SHARE_ALL = FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE

# Creation disposition
CREATE_NEW = 1
OPEN_EXISTING = 3

# Flags
FILE_FLAG_BACKUP_SEMANTICS = 0x02000000
FILE_FLAG_OPEN_REPARSE_POINT = 0x00200000
FILE_FLAG_REPARSE_BACKUP = FILE_FLAG_OPEN_REPARSE_POINT | FILE_FLAG_BACKUP_SEMANTICS

# File attributes
FILE_ATTRIBUTE_NORMAL = 0x00000080
FILE_ATTRIBUTE_DIRECTORY = 0x00000010
FILE_ATTRIBUTE_REPARSE_POINT = 0x00000400
INVALID_FILE_ATTRIBUTES = 0xFFFFFFFF

# Volume capability flags (GetVolumeInformation lpFileSystemFlags)
FILE_SUPPORTS_HARD_LINKS = 0x00400000
FILE_SUPPORTS_REPARSE_POINTS = 0x00000080

# Device/method/access codes for CTL_CODE()
FILE_DEVICE_FILE_SYSTEM = 0x00000009
METHOD_BUFFERED = 0
FILE_ANY_ACCESS = 0
FILE_SPECIAL_ACCESS = FILE_ANY_ACCESS


def CTL_CODE(device_type: int, function: int, method: int, access: int) -> int:
    return (device_type << 16) | (access << 14) | (function << 2) | method


FSCTL_GET_NTFS_FILE_RECORD = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 26, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_SET_REPARSE_POINT = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 41, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
FSCTL_GET_REPARSE_POINT = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 42, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_DELETE_REPARSE_POINT = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 43, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

# Reparse point tags
IO_REPARSE_TAG_MOUNT_POINT = 0xA0000003
IO_REPARSE_TAG_SYMLINK = 0xA000000C

# Symbolic link buffer flags
SYMBOLIC_LINK_FLAG_RELATIVE = 1

# Reparse data buffer size limit (from ntifs.h)
MAX_REPARSE_BUFFER_SIZE = 16 * 1024

# NT namespace prefix used for absolute substitute names
PATHNAME_PREFIX = '\\??\\'
PATHNAME_PREFIX_LEN = len(PATHNAME_PREFIX)

# Privilege names
SE_BACKUP_NAME = 'SeBackupPrivilege'
SE_RESTORE_NAME = 'SeRestorePrivilege'
SE_CREATE_SYMBOLIC_LINK_NAME = 'SeCreateSymbolicLinkPrivilege'
SE_PRIVILEGE_ENABLED = 0x00000002
TOKEN_ADJUST_PRIVILEGES = 0x0020
TOKEN_QUERY = 0x0008

# Well-known NTFS MFT record index for a volume's root directory.
NTFS_ROOT_DIRECTORY_FRN = 5

# FILE_NAME attribute NameType values (see FILENAME_ATTRIBUTE.NameType)
NTFS_FILENAME_TYPE_POSIX = 0x00
NTFS_FILENAME_TYPE_WIN32 = 0x01
NTFS_FILENAME_TYPE_DOS = 0x02
NTFS_FILENAME_TYPE_WIN32_AND_DOS = 0x03

# $MFT attribute type codes (only the one we need to walk)
ATTRIBUTE_TYPE_FILE_NAME = 0x30
ATTRIBUTE_TYPE_END = 0xFFFFFFFF


def strip_pathname_prefix(path: str) -> str:
    if path.startswith(PATHNAME_PREFIX):
        return path[PATHNAME_PREFIX_LEN:]
    return path
